services:
  postgres:
    image: postgres:17.5-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - btc-game-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres
      - redis
    command: >
      sh -c "npm run migration:run && npm run start:prod"
    environment:
      - ${NODE_ENV}=${NODE_ENV}

volumes:
  btc-game-db: