name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/btc-game
          git pull origin main
          
          # API 
          cd api
          npm install
          npm run build
          pm2 describe nestjs-app || pm2 start dist/main.js --name nestjs-app
          pm2 restart nestjs-app

          # Client
          cd ../client
          npm install
          npm run build
          sudo rm -rf /var/www/html/*
          sudo cp -r dist/* /var/www/html/
          sudo chown -R nginx:nginx /var/www/html
          sudo chmod -R 755 /var/www/html

          # Reload nginx
          sudo systemctl reload nginx
